export const mockArticle = {
  abstract: 'Abstract',
  web_url: 'https://www.example.com',
  snippet: 'Snippet',
  lead_paragraph: 'Lead Paragraph',
  print_section: 'Print Section',
  print_page: 'Print Page',
  source: 'Source',
  multimedia: [
    {
      rank: 0,
      subtype: 'xlarge',
      caption: null,
      credit: null,
      type: 'image',
      url: 'images/2024/11/22/multimedia/22xp-embezzle-County-building/22xp-embezzle-County-building-articleLarge.jpg',
      height: 400,
      width: 600,
      legacy: {
        xlarge:
          'images/2024/11/22/multimedia/22xp-embezzle-County-building/22xp-embezzle-County-building-articleLarge.jpg',
        xlargewidth: 600,
        xlargeheight: 400,
      },
      subType: 'xlarge',
      crop_name: 'articleLarge',
    },
  ],
  headline: {
    main: 'Main',
    kicker: null,
    content_kicker: null,
    print_headline: 'Print Headline',
    name: null,
    seo: null,
    sub: null,
  },
  keywords: [],
  pub_date: '2024-10-30T20:32:06+0000',
  document_type: 'document_type',
  news_desk: 'news_desk',
  section_name: 'section_name',
  byline: {
    original: 'Original',
    person: [],
    organization: null,
  },
  type_of_material: 'type_of_material',
  _id: 'nyt://article/a18df93d-8cdd-56ee-bff8-816a53498afb',
  word_count: 0,
  uri: 'uri',
};
